# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/ip/inst_mem_2/inst_mem_2.xci
# IP: The module: 'inst_mem_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/ip/inst_mem_2/inst_mem_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/ip/inst_mem_2/inst_mem_2.xci
# IP: The module: 'inst_mem_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/ip/inst_mem_2/inst_mem_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
