# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Administrator/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-7456-DESKTOP-RFT92PT/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/VerilogPrograms/pipelined/pipelined.cache/wt [current_project]
set_property parent.project_path E:/VerilogPrograms/pipelined/pipelined.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/VerilogPrograms/pipelined/pipelined.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/VerilogPrograms/coe/mipstest.coe
add_files E:/VerilogPrograms/coe/1.Ori_Inst_Test/inst_rom.coe
add_files E:/VerilogPrograms/coe/2.Logic_Inst_Test/inst_rom.coe
add_files E:/VerilogPrograms/coe/3.Shift_Inst_Test/inst_rom.coe
read_verilog E:/VerilogPrograms/define/define.vh
read_verilog -library xil_defaultlib {
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/adder.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/alu.v
  E:/VerilogPrograms/PCandController/PCandController.srcs/sources_1/new/aludec.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/controller.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/datapath.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/eqcmp.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/flopenr.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/flopenrc.v
  E:/VerilogPrograms/singleCPU/singleCPU.srcs/sources_1/new/flopr.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/floprc.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/hazard.v
  E:/VerilogPrograms/PCandController/PCandController.srcs/sources_1/new/maindec.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/mips.v
  E:/VerilogPrograms/singleCPU/singleCPU.srcs/sources_1/new/mux2.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/mux3.v
  E:/VerilogPrograms/singleCPU/singleCPU.srcs/sources_1/new/regfile.v
  E:/VerilogPrograms/singleCPU/singleCPU.srcs/sources_1/new/signext.v
  E:/VerilogPrograms/singleCPU/singleCPU.srcs/sources_1/new/sl2.v
  E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/new/top.v
}
read_ip -quiet E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all e:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/ip/inst_mem/inst_mem_ooc.xdc]

read_ip -quiet E:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all e:/VerilogPrograms/pipelined/pipelined.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
